### PR TITLE
Implement --cn flag to override headers.cn

### PR DESCRIPTION
**Pull request by kriskowal**
r @jakev @abhinav

### CODE REVIEW

**Comment by kriskowal** [comment]
See #119 for motivation for `--cn fake --sneaky` usage.

**Comment by abhinav** [comment]
LGTM

**Comment by blampe** [comment]
We do have some services currently whitelisting "tcurl" in particular for health checks soooo maybe break it into 2 diffs? First to add the option, update health checks to continue identifying as tcurl, then change default behavior.

**Comment by Raynos** [comment]
Agreed; let's avoid changing the health check behaviour. it should probably be "sneaky" by default.

**Comment by kriskowal** [comment]
Backed out the appended commits and amended to “be sneaky by default”

**Comment by DAddYE** [comment]
Shouldn't this be documented in the command line help?

**Pull request merged**
