### PR TITLE
Add transport header argv closes #28

### LINKED ISSUE #28: Need the ability to send Ringpop Transport Header
tcurl doesn't have a --headers flag that allows us to send transport tchannel headers

### PR DESCRIPTION
**Pull request by rssathe**

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by jcorbin** [comment]
This probably makes sense for now, but:
- transport headers are meant to be internal, not arbitrarily extensible by the user
- we should be sure that either tchannel itself or tcurl does a break-early, break-hard check for invalid headers before just sending them
- I'd really like to understand your need / use case better, and sort out why whatever transport header you needed to set wasn't being set

Chances are high that things that are "transport headers" in v2 will shift to be a first class fixed field in v3 (e.g. the cn header), so I really consider exposing transport headers to be a maintenance liability.  That all said, the current state of the tcurl tool is quite debt-ridden, and we need to change a lot of things (perhaps including the entire CLI experience).

**Comment by Raynos** [comment]
@jcorbin 

The use case is `--headers='{"sk":"uuid"}'` for tcurling ringpop services.

TChannel already exposes headers as an arbitrary string/string bag you can put any data you want into. We really need to make a breaking change there if the desire is to limit transport headers.

**Comment by malandrew** [comment]
Ugg, stupid git rebase. Can I just squash all these commits and force push over this branch (or push onto a new branch) so this produces a clean history after merging with master?

cc/ @Raynos @rssathe

**Comment by rssathe** [comment]
@malandrew fine by me

**Pull request closed without merging**
