### PR TITLE
tcurl + as-json test

### PR DESCRIPTION
**Pull request by ShanniLi**
r @Raynos @kriskowal 

1. tcurl included
2. added a test: as-json.

I will publish the package after merge.

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by kriskowal** [comment]
Please break this into two commits.

**Comment by Raynos** [comment]
it's easier to review if broken into "copied bin/tcurl.js" commit and "edited index.js" commit.

**Comment by kriskowal** [comment]
This has been superseded by #4. @ShanniLi In the future, you can force push over a branch to update the corresponding PR instead of making a new one.

**Pull request closed without merging**
