### PR TITLE
Parse Thrift forgivingly

### PR DESCRIPTION
**Pull request by kriskowal**
r @Raynos @ShanniLi

### CODE REVIEW

**Comment by Raynos** [comment]
:-1:

Spoke with @blampe 

We should just be strict by default and make the breaking change where we force developers to write good IDLs

If we really want to allow this then we can add a `--no-strict` flag.

**Comment by kriskowal** [comment]
For TCurl, it makes sense to be forgiving by default. TCurl is for interrogating prod, not for linting the IDL.

**Comment by ShanniLi** [comment]
Agree with @Raynos, we better go strict now than later. TCurl should not be exempt, since it sends requests to services. Both sides should be treated equally.

**Comment by prashantv** [comment]
`tcurl` is a tool, not a production service or client, and should allow using non-strict `.thrift` files. You don't want to be debugging a production issue and be slowed down because a tool refuses to work.

I like the idea of hiding it behind a flag -- I think it should be similar to how `wget` treats invalid SSL certificates. By default it does not work, but it tells you clearly how you can get around it by passing `--no-check-certificates`.

**Comment by blampe** [comment]
+1 to `--no-strict` or `--forgiving`.

**Comment by ShanniLi** [comment]
If we plan to enforce 'strict', it doesn't matter it is a tool or not. Getting away from tcurl won't help, since the server side will still have the same check.

I am actually OK either way (strict or no-strict), but all sides should be consistent w.r.t. the policy.

**Comment by prashantv** [comment]
The tool generates binary that is sent to the server - this binary data doesn't change either way. E.g. a field in a struct (optional or required or not specified) is encoded the exact same way.

So no, the server will not reject this binary data. The server will reject bad .thrift files when starting up which is fine. Tools are often used for debugging and so should be more relaxed.

**Comment by ShanniLi** [comment]
How about the thrift client? tcurl cann't be the only one talking to the server. :)

**Comment by prashantv** [comment]
This PR is only about tcurl. The client should also use strict mode, any production services and clients will validate in strict mode.

**Comment by ShanniLi** [comment]
I mostly see two ways tcurl being used:
1. during development, tcurl is used to hit a service endpoint. In this case, tcurl acts like a client. Inconsistency behaviors between tcurl and client cause confusions.

2. debugging production: at this stage, if we decide to enforce the strict requirement, IDLs should already be in good shapes. Also, tcurl should prevent any bad IDL being used against production servers. 

Both scenarios favor strict mode and the consistency across all usages.

**Comment by prashantv** [comment]
1. If you're using it during development, your server will throw the error, not tcurl. You shouldn't rely on tcurl at all. And by default, tcurl WILL throw the error, so it's consistent.

2.And break all existing services that are not using strict right now? If some service has an outage tomorrow, do you think "sorry, tcurl only supports strict mode" is a good reason to stop them from debugging their service?

We can use strict mode by default, I'm just saying we need an option to disable it. Until we're in a world where strict mode is enforced everywhere and we're sure there's no non-strict Thrift files around, we cannot force it upon everyone using a tool.

**Comment by ShanniLi** [comment]
1. It is inconsistent if tcurl behaves differently compared to service/client.
2. Servers use thrift IDL much earlier than tcurl (what to curl without a service up and running?). So, if server will throw the error, there will be no error to throw when tcurl is used on the IDL. The reason we see complaints is because we just started to enforce the strict rules. 
3. I don't really see how the usage about debugging existing service using tcurl being true ... We are just starting, so it is the right time to enforce things if we ever want to enforce any.

**Comment by prashantv** [comment]
We have non-zero production services that are not using strict Thrift right now, so you cannot start enforcing strictness in tools that are used for debugging. That is enough to make this a non-starter.

Let's discuss this in person tomorrow, this thread has gotten too long (and repetitive) to be productive.

**Comment by Willyham** [comment]
As a concrete example, I ran into this problem yesterday when trying to debug an issue and another team's service had a non-strict IDL. Having a `--no-strict` flag would have been really helpful there.

**Comment by kriskowal** [comment]
I argue that it would have been even more helpful if it had just worked™.

**Comment by Raynos** [comment]
:+1: --no-strict

**Comment by Willyham** [comment]
@kriskowal I actually agree with you there. I don't see any reason to enforce it in the tool but everyone else seems to feel strongly about it.

**Pull request closed without merging**
