### PR TITLE
Withdraw as=http support

### PR DESCRIPTION
**Pull request by kriskowal**
Because ThriftAsHTTP does not provide a stable public interface for issuing requests.

r @ShanniLi @malandrew 
cc @raynos @jcorbin

### CODE REVIEW

**Comment by ShanniLi** [comment]
cc @anson627 @davewhat

**Comment by anson627** [comment]
We don't have to remove it. Xlate doesn't use it now, but it doesn't mean it won't be useful for app developer. Instead of calling sendRequest, we should call forwardToChannel, which is designed to be public interface and should be kept backward compatible. We should make sendRequest private.

**Comment by kriskowal** [comment]
@anson627 Please take ownership of tcurl as=http and submit a PR to that effect. Thanks.

**Comment by anson627** [comment]
@kriskowal Sure, I will make sure tcurl is up to date.

**Pull request closed without merging**
