### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prashantv**
Update the latest command line options in the README

r: @ShanniLi @Raynos

### CODE REVIEW

**Comment by kriskowal** [comment]
♗ :sweat_drops:

**Comment by ShanniLi** [comment]
This is out of date. May be just reference to https://github.com/uber/tcurl/blob/master/usage.md ?

**Comment by prashantv** [comment]
Not sure what you mean by out of date @ShanniLi  - this is from the latest version of tcurl v4.14 which is the current version in master.

Like the idea of linking to usage - added a link. I think it's nice to have the very short command line usage on the README as well so keeping that.

**Comment by ShanniLi** [comment]
This is not the current tcurl help output anymore. We used to just copy/paste the tcurl help output to the README. I guess it needs to be manually maintained now.

**Comment by kriskowal** [comment]
Let’s write a script that runs tcurl --help and syncs up the prose in usage.md and thus the man page. Add a test to the suite to ensure they’re in sync.

**Comment by ShanniLi** [comment]
@kriskowal the script already exists:
npm run man

Need some help with the idea about how to write this test. :)

**Comment by ShanniLi** [comment]
@kriskowal  this should help a little more:
https://github.com/uber/tcurl/commit/3cd2575dde69846f12f425bb646068cd11cfdf96

**Pull request merged**
